import type { LucideIcon } from "lucide-react"
import {
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  Blocks,
  BookOpen,
  Cake,
  Calculator,
  CalendarDays,
  CircleCheckBig,
  Clipboard,
  Coffee,
  Crosshair,
  Crown,
  Equal,
  FolderPlus,
  Folders,
  Globe2,
  HandCoins,
  Handshake,
  Heart,
  History,
  House,
  Languages,
  Landmark,
  LayoutGrid,
  Library,
  Lock,
  Megaphone,
  Network,
  Notebook,
  PartyPopper,
  PieChart,
  Pencil,
  Percent,
  Plane,
  ReceiptText,
  Ruler,
  Shapes,
  Shield,
  Sparkles,
  Star,
  Trophy,
  UserCheck,
  UserRoundPlus,
  Users,
  Utensils,
  Wallet,
  WalletCards,
} from "lucide-react"

// Соответствие строковых иконок ачивок (из lib/achievements.ts) компонентам
// lucide. Используется и в списке ачивок в профиле, и во всплывающем тосте.
export const achievementIconMap: Record<string, LucideIcon> = {
  "badge-check": BadgeCheck,
  "badge-dollar": BadgeDollarSign,
  banknote: Banknote,
  blocks: Blocks,
  "book-open": BookOpen,
  cake: Cake,
  calculator: Calculator,
  calendar: CalendarDays,
  "chart-pie": PieChart,
  "circle-check": CircleCheckBig,
  clipboard: Clipboard,
  coffee: Coffee,
  crosshair: Crosshair,
  crown: Crown,
  equal: Equal,
  "folder-plus": FolderPlus,
  folders: Folders,
  globe: Globe2,
  "hand-coins": HandCoins,
  handshake: Handshake,
  heart: Heart,
  history: History,
  house: House,
  languages: Languages,
  landmark: Landmark,
  "layout-grid": LayoutGrid,
  library: Library,
  lock: Lock,
  megaphone: Megaphone,
  network: Network,
  notebook: Notebook,
  "party-popper": PartyPopper,
  pencil: Pencil,
  percent: Percent,
  plane: Plane,
  receipt: ReceiptText,
  ruler: Ruler,
  shapes: Shapes,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  "user-check": UserCheck,
  "user-plus": UserRoundPlus,
  users: Users,
  "users-round": Users,
  utensils: Utensils,
  wallet: Wallet,
  "wallet-cards": WalletCards,
}

// Иконка ачивки по строковому ключу; Trophy — запасной вариант.
export function getAchievementIcon(name: string): LucideIcon {
  return achievementIconMap[name] ?? Trophy
}
